### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#335]
- [ ] Move over ODB domain
- [ ] Start request data run
- [ ] update blog
- [ ] final test of all systems on dev ( @meganwaps & me )
- [ ] re-test everyting on live ( @meganwaps & me )

**Comment by JosephMcArthur** [comment]
Joe, little reminder:
* https://docs.google.com/spreadsheets/d/1vmGu0wPgpgMGHOBeJzq9lhbXAZuYRF1nc1cffQZTb3g/edit?ts=580539f5#gid=1751613084
* https://docs.google.com/document/d/1Zp-sf_JqNMw8keXD11pnTGUOqbGf-7QZugNrxPo-7AA/edit#

you need to do another test of mobile, just to make sure.

**Comment by JosephMcArthur** [comment]
@markmacgillivray I'm being told by the chrome store:

> Invalid version number in manifest: 0.2.5. Please make sure the newly uploaded package has a larger version in file manifest.json than the published package: 0.8.8.

Can you make that happen plz?

**Comment by markmacgillivray** [comment]
New https security sets force https using hsts, which is nice when in use, but annoyingly when you want to cancel it to repoint the domain somewhere else, there is no way to do so without leaving the old domain up and hoping everyone eventually visits it. So I have left opendatabutton.org pointing to a page that says go to openaccessbutton.org, and that is as good as is possible.

**Comment by markmacgillivray** [comment]
I have installed a plugin direct from chrome store now, using the button on our /account page. I am going to move on to getting the old data copied over.

**Comment by markmacgillivray** [comment]
I checked restart blocking, not a problem when installed officially from chrome. Also have done sanity check of plugin and site, seems fine. Would be good to get someone else go through it though.

**Comment by markmacgillivray** [comment]
Request data run has been improved and will be running at various points throughout the day and over the weekend.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can't see any requests being added, can we get this moving?

**Comment by JosephMcArthur** [comment]
@markmacgillivray what's the story on getting archive requests up?

**Comment by markmacgillivray** [comment]
@JosephMcArthur to be discussed today, sorry it keeps getting delayed - I believe now the final issue is to switch to using URLs that we normalise down to not including the ? or # information. We had previous discussions around this for the plugin side of things, and it DOES send these in the URL because if we ever do want to do something with pages that use these URL params we would need them. However, it makes it too hard to normalise URLs at the backend as we are seeing too many sites using unique identifiers within these strings.

So this means that to finish the old data load I first have to go through the NEW requests, about 75 at the moment, and reduce them to just the URLs without the ? or # and wherever this creates new duplicates I will make the others a support of the first request for that URL. Then I can load in the old requests and similarly dedupe them.

If we confirm this is OK in the meeting today, then I will do this first thing in the next sprint.

**Comment by JosephMcArthur** [comment]
This is okay.

**Comment by markmacgillivray** [comment]
The old data / new data issue continues to be increasingly annoying. As this issue has become a kind of placeholder for it, I am writing some updates here.

Had hoped to simplify URLs down to without the query params, although did not do this initially because of concerns about how to represent search pages. Decided to do this, so that we could dedupe things easier, but found that not only do search sites use query params to identify queries - which we could safely ignore for now, although would make things complicated later - but some sites use the query params to identify pages that can actually appear to be the article itself. Unfortunately, NCBI is one of these, and that is a big one.

So we are not going to be able to dedupe by simplifying URLs. I have been considering options for simplifying in specific cases, but there is no reliable way. For example:

If a URL comes in with query params / hash values, look for URLs already in the system with identical main URLs but different params; this would show that the params are identifying a unique page, but would NOT show if that page is an article page or just a search page.

If a URL comes in with params but the main URL itself is NOT already in the system, assume the main URL is enough to identify the page. This would work IF we already knew that certain main URLs are ones where this works, but will not otherwise, because the first such URL into the system will be unique so will be saved without the query params. But then, subsequent URLs will match that one in the system, so will never be unique, so will never be saved without query params. This sounds like it would work, except if we save the first ever such URL without query params, it will be wrong. If we save the first ever such URL with query params, we get the following paradox:

Receive a URL:
* no query params / hashes, save it
* query params / hashes - look for any request with main URL already, ignoring params
* if any with same main URL exist, save with params
* if none with same main URL exist, save with params
* so now we are saving all URLs that come in with params

The only solution would appear to be to pre-populate with URLs we KNOW require the params for actual unique identification. but, with no way to know which sites users will use the button on, and legitimate use being possible on many thousands if not millions of sites - and new ones in future that we do not even know about yet - this seems futile.

What about saving the first ever URL without params, even if that makes it wrong? This may not be too bad, and we could do the subsequent URL check as exact match of main URL portion. So e.g. if find scholar.google.com alone in the system, we know the next one that looks like scholar.google.com?q=thing DOES need the params to uniquely identify. BUT this does not work either. Because if someone does go to a URL of an actual article page on certain publisher sites and gets the main URL without params (which is possible) then we will have that URL in the system without params. If another user then goes to that URL and DOES get some params - e.g. session identifiers etc, then we would NOT match their URL with the first one, because it would appear as if the main URL is a search page. So this still would not work.

The only option appears to be to revert (again...) to keeping URLs fully as they are submitted to the system. This does mean it is easier once again to import the old records, and could be easier to integrate search sites in future, but still leaves us with the problem of unwanted duplicates.

At this stage, I think the only solution can be to have a dedupe run where we can get additional metadata - if we CAN find a DOI for a page, or a title, and if we CAN find an identical DOI or title in previous requests, then we could assume the user wants the same thing EVEN IF they are on a different URL. However this could mean there could be multiple URLs for a given request - our working practice up to now has been that the button is a thing that works on URLs, not on DOIs etc. This has been discussed in previous issues.

We could also have manual deduping - an addition to the UI to allow admins to say "this is a dupe" and to merge with the duplicate record. This would have the same issue as above though, in that if the URLs are actually different, we would need to record both URLs against the deduped request.

If we don't record the multiple URLs, the next time a user asked for the one we threw away we would loop back into this problem again.

We may have to make a decision on this sooner than we had desired. Otherwise, whatever way we try to do, things are getting messed up in at least one of the undesirable ways.

This means the main question is:

* should we move away from thinking of URLs as unique entities?

and:

* if so, what do we count as unique? DOIs?

Note too: it is not possible to guarantee we correctly identify a DOI for any given web page. Sometimes they just cannot be reliably extracted. And this is particularly the case on the pages most likely to land us in this problem, e.g. search-generated pages that actually have URLs that display the landing page of an article.

Plus of course, for pages that do not have DOIs, or where the DOI cannot be found, we could not solve this problem using DOIs.

I am inclined to think at this stage we stick with full URLs including params as the unique identifier, and later we add in a manual method for admins to close some requests as dupes. Where they do, the request should still EXIST so we can match people to that URL, but when they go to the request, they would find it is closed and that it links as a duplicate to another request.

This may sound like clunky UI, but it does work well in other contexts - think duplicate questions on stackoverflow - you still land on them if you search, but then you follow the link to the one that has been marked as the canonical one.

To discuss at later meeting, then decide. I am going to move this into the current milestone to ensure we follow up and can then close by moving the old data with URLs as we decide best, and then create new issue for the UI dupe work in the next milestone.

**Comment by markmacgillivray** [comment]
First batch of 1000 went fine. 

Second batch had none from known users (that is OK, we know we will lose about 3000 of the total from very old accounts).

Third batch only seems to have retrieved about 60, and not sent the completion email. Re-check this lot for anything erroring out. Have updated the code to just rerun a batch and ignore those it already processed, so rerunning it again.

**Comment by markmacgillivray** [comment]
So, there still appear to be occasional dropouts of very large data loads through phantom, but not as bad as they were when we started. And rerunning now picks up whatever was missed. And having gone over and over the best ways to match the URLs, or at least having picked the least bad way, it appears to be actually working well enough!!! I have not deleted the first two batch attempts on the live server, and the third is rerunning again now. Will keep adding notes here to remind me how far through I am.

**Comment by markmacgillivray** [comment]
Third batch completed (from 2000)

**Comment by markmacgillivray** [comment]
fourth batch finished whilst I was asleep, no issues. Running next one now.

**Comment by markmacgillivray** [comment]
spotted a uri error in catalogue.extract flash by, that could be the cause of the occasional fallouts. Will add extra try/catch to that. That would be good, if the URL is malformed then we are falling over on ones that must be invalid anyway. Will do a search on the old data to verify. Kicking off the 4000 batch again.

**Comment by markmacgillivray** [comment]
batch 4000 done

**Comment by markmacgillivray** [comment]
5000 done

**Comment by markmacgillivray** [comment]
6,7,8000 ran fine, 9000 fell over once, then seemed to hang indefinitely with 100% cpu on a phantomjs process. Restarted app and kicked off 9k again

**Comment by markmacgillivray** [comment]
9k done, 10k done with no users for blocks in that range

**Comment by markmacgillivray** [comment]
11k done, 12k no users

**Comment by JosephMcArthur** [comment]
For ones without users attached, what are we doing with them?
